### ISSUE TITLE
Cannot import 'BasePipeline'

### ISSUE THREAD

**Issue by saps13** [RedisLabs/rejson-py#15]
I am running into
`ImportError: cannot import name 'BasePipeline' from 'redis.client' (/usr/local/lib/python3.7/site-packages/redis/client.py)`

at this line

`from rejson import Client, Path`

Issue occurs with redis-py version 3.0.1

**Comment by arulmuruganas** [comment]
Facing the same issue

**Comment by gkorland** [comment]
See #17
